### PR TITLE
Fix drawing of blinded overlay in log scale. Fixes #46

### LINKED ISSUE #46: Blinded range overlay is broken in log-scale

### PR DESCRIPTION
**Pull request by blinkseb**
It's not easily possible to retrieve the Y-axis maximum when log-scale is on (see [here](https://root.cern.ch/phpBB3/viewtopic.php?t=10745) for more details, 2010...), so we implement a workaround for drawing the blinded-range overlay on the plot when logscale is on.

### CODE REVIEW

**Comment by OlivierBondu** [comment]
it seems it now needs to be rebased after the previous merge, sorry about that

**Comment by blinkseb** [comment]
Ah yes will do it right now

**Comment by blinkseb** [comment]
@OlivierBondu Done :)

**Comment by OlivierBondu** [comment]
travis failed but it looks like it could be a temporary glitch... Is there a way to retrigger it ?

**Comment by blinkseb** [comment]
Ah indeed, it's cause I generated the golden image for this PR with the previous systematics, so it's not consistent anymore. I'll regenerate them and update the PR

**Pull request merged**
