### PR TITLE
Logarithmic y-axis range: find the smallest minimum in the stack

### PR DESCRIPTION
**Pull request by pieterdavid**
Currently, the minimum of the "last" histogram in the processed stack (i.e. the sum of all contributions) is used, which may hide some small contributions (especially in histograms with few bins that all have many entries). So this looks for the smallest minimum in the whole stack instead (maybe the loop is a bit too paranoid, unless there are negative histograms or the order changes, the first will be the smallest). Do you agree?

### CODE REVIEW

**Comment by blinkseb** [comment]
Cool, this is something I had in mind since a long time! As expected, the reference images are no longer valid, can you regenerate them please? (Simply switch https://github.com/cp3-llbb/plotIt/blob/master/test/unit_tests/tests.py#L125 to `True` and execute `run_tests.sh` from tests/

**Comment by pieterdavid** [comment]
Thanks, looking at the reference images, the "margin" at the bottom becomes a lot larger this way, so maybe the safe_margin value should be adjusted a bit as well... (compare http://i.imgur.com/M9WiGvx.png with the reference http://i.imgur.com/eAUZtON.png)

**Comment by blinkseb** [comment]
Thinking a bit more about it, I'm in fact not expecting the plot to change, since the last element in the stack is the smallest background here. Do you have an idea of what's happening?

**Comment by pieterdavid** [comment]
Calling `Print` on the `THStack::GetStack` list gives increasing numbers of entries, that's why I assumed the last one is actually the sum of all of them, I'll have a closer look

**Comment by pieterdavid** [comment]
Hypothesis confirmed: we were taking the minimum of the highest histogram. I didn't realise before that this only sets the minimum, and ROOT adds a margin on top of that... what I would propose then is to set set the lowest value in the bottom histogram of the stack as minimum (ROOT adds more to make sure this is not on the edge anyway) - that's what my last commit does. The modified reference image then becomes http://i.imgur.com/2gBn2xf.png, not too much larger a range than the original (and it shows that the bin just above 3 has an entry in MC2). Is that acceptable?

**Comment by blinkseb** [comment]
Arf my bad then, I messed up in the order of the stack. It's indeed much better, but are you sure ROOT adds automatically a _safe_ margin? It'd would kind of defeat the purpose of having `SetMaximum` / `SetMinimum` methods.

I'm also a bit puzzled by the fact that the legend text size vary from one image to another, probably a new ROOT mystery!

Thanks!

**Comment by pieterdavid** [comment]
It was bigger than the factor 8 before I removed that, and both the lowest bin in my two-bin histograms and the 1-entry bins in the tails of distributions are nicely displayed now, so I am reasonably certain about the margin. `SetMinimum` and `SetMaximum` set the input values for ROOT's calculation (my understanding - reference missing), if you want to override that, it's better to use `SetRangeUser`.
I thought the legend text size was due to my pdf viewer... my best guess is that it is due to the change from "Uncertainties" to "Uncertainty" in https://github.com/cp3-llbb/plotIt/commit/365e222e2089aa671123ca75a2cc729aba7d7536 which may have stayed below threshold (?) so far - ROOT scales font sizes according to the available space.

**Comment by blinkseb** [comment]
Cool then, it makes sense indeed, both for the margins and the legend. So I guess we'll also need to later remove the manual safe margin for non-log plots too?

Anyway, many thanks!

**Comment by pieterdavid** [comment]
Maybe... I left it even at the top of log plots for now because the legend positioning counts on having enough white space there

**Pull request merged**
