### PR TITLE
Add basic unit tests

### PR DESCRIPTION
**Pull request by blinkseb**
Tests run plotIt to produce histograms, and check that the produced
pictures is identical to a reference image.

Currently, only a default plot with and without ratio are produced,
but we can easily add more test cases.

In the future, we may also want to start doing real unit-testing by
testing piece of code...

These tests are automatically ran by Travis for each build. I hope this will help to detect bugs before PR are merged :)

### CODE REVIEW

**Comment by swertz** [comment]
Will there be an easy way to view the test's plots? 
There's always a risk for unit tests to be counterproductive since each time we add something to the plots or purposefully modify a functionality, the test would fail. 
If other people have a way to easily check the changes without having to pull & build then it's a big :+1:

**Comment by blinkseb** [comment]
Well, it's exactly what unit tests are for: detect changes in code. If these changes are correct, you should also update unit tests to make them passed again.

At some point, we should start thinking about backward compatibility. If you want to redraw a plot year(s) later with the same configuration, you should have the exact same output. This is what is tested here: for a given configuration, you should always have the same output. If it's not the case, then something is wrong.

> If other people have a way to easily check the changes without having to pull & build then it's a big :+1:

If I understand correctly, you would like to have a way to see the plots produced by the unit tests? It's not possible with this PR (all the plots are saved in /tmp and overwritten each time). It should be possible to upload the plots and print the url to the log file. Do you think it'd be useful?

**Comment by OlivierBondu** [comment]
I'd say it's useful to at least have the reference plot somewhere, and the other one if the unit test failed ?

**Comment by blinkseb** [comment]
Ok so I've updated the PR. If a test fails, the images with be uploaded and the following text will be shown in build log:

```
Images uploaded:
 - Reference image: http://i.imgur.com/RY3QVp9.png
 - Generated image: http://i.imgur.com/4RiGH7r.png
 - Difference: http://i.imgur.com/aFspYtL.png
-----

To delete image, execute these commands:

curl -X DELETE -H "Authorization: Client-ID e32a7007635bb1f" https://api.imgur.com/3/image/MJLXMdR5W85DVL7
curl -X DELETE -H "Authorization: Client-ID e32a7007635bb1f" https://api.imgur.com/3/image/wSGqD9ouOXY771Q
curl -X DELETE -H "Authorization: Client-ID e32a7007635bb1f" https://api.imgur.com/3/image/Qbbvz3B5LEOskZC

-----
```

We can upload a maximum of 12500 images per month, but I guess it's enough for our usage ;)

**Comment by OlivierBondu** [comment]
thanks !

**Pull request merged**
