### PR TITLE
New features

### PR DESCRIPTION
**Pull request by blinkseb**
Two new features:
- Add a way to change the 'Uncertainties' label on the plot. Default value is now 'Uncertainty' instead of 'Uncertainties'
- Add a way to insert custom entries in the legend at a given position.

``` yaml
legend:
    entries:
      -
        label: 'Legend label'
        type: 'mc'   # 'signal' or 'data' is also possible
        order: 1000  # Force on top
      -
        label: 'Legend label 2'
        type: 'signal'
        order: 1000
```

### CODE REVIEW

**Comment by swertz** [comment]
So, you're updating the twiki page?

**Comment by blinkseb** [comment]
Someone should do it yeah :) I should have some spare time later to do it

**Comment by swertz** [comment]
Thanks! However I'm not sure I understand the PR: when you say "additional entries" what do you mean by that? I see in the diff that you go look for files...

**Comment by blinkseb** [comment]
No,the diff is a bit misleading because I renamed the struct `Entry` to `LegendEntry` before moving it to the types.h file. Interesting part starts here: https://github.com/cp3-llbb/plotIt/pull/69/files#diff-8ea05427ed1e264915a5a24ee5a597b5R715

This change allow to add arbitrary entries into the legend no backed by an histogram. For example, in the plot below, the legend entry 'Signal (1 pb)' is added manually to the 'signal' legend block
(plot removed)

**Comment by swertz** [comment]
Oh I see, great, thanks!

**Comment by OlivierBondu** [comment]
(now that the PR is closed, could you remove the plot from the public web ?)

**Pull request merged**
