### PR TITLE
Rework systematics implementation

### PR DESCRIPTION
**Pull request by blinkseb**
Ok so this is a big change in how systematics are handled in plotIt. Previous way was not suitable and very buggy, so this is a fresh start.

You now specify a list of systematics using the... `systematics` options in the configuration file. First, an example of the expected format:

``` yaml
systematics:
  - alpha # Shape systematics
  - beta: {type: shape}  # Shape systematics
  - gamma: {type: ln, prior: 1.072, pretty-name: "Gamma"}  # Log-normal systematics, +7.2%, -2.97%, exp(+/- 1 * log(prior))
  - delta: 1.14  # Constant systematics, +- 14%
```

It's an array of either a string of a map. In each case, the string or map key is the name of the systematics. This name is mainly used in the summary output, but also to find histograms in the case of shape systematics.

There's currently 3 types of systematics supported for the moment:
- Shape systematics (`type = shape`). This is the default one used when no `type` is specified
- LogNormal systematics (`type = ln` or `type = lognormal`). The `prior` option is mandatory, and you can also specify the `post-fit` and `post-fit-error` values for post-fit uncertainties, which are by default `post-fit = 0` and `post-fit-error = 1` in order to consider +- 1 sigma. Note: this is an asymmetric systematics. However, the code does not handle this for the moment, and use the biggest variation, so currently, it'll behave as if it was symmetric.
- Constant systematics (`type = const`). Apply only +/- the given value to get the uncertainty. It's basically the same thing as a log-normal systematics pre-fit, but it's symmetric. There's also no post-fit options here.

For shape systematics, you have to provides two new distributions, one for the `up` variation, and one for the `down` variation. plotIt will use the name of the systematics to look for the shape:
- First, it'll look for a shape inside the main file named `<plotname>__<systematics>[up|down]` (note that it's 2 `_`).
- If no such shape is found, it'll try to look for a shape named `<plotname>` in a file named `<nominalfile>__<systematics>[up|down].root`.
- If still not found, the systematics is ignored.
### Treatment of systematics

I've fixed some issues in the previous way of combining systematics. What is done now is:
- Consider that the **same systematics** in **different bins** and **different process / files** are totally **correlated**. Previously they were treated as non-correlated, which is wrong.
- Consider that **different systematics** in the _same bin_\* are non-correlated

I'd great if someone can confirm this is the proper thing to do :smile: 

There was also a bug in the drawing of the systematics band in the ratio, the band was twice too small... I've done some basic testing, like adding a 25% systematics and seeing that the band  in the ratio is flat between 0.75 and 1.25 (so +25% everywhere), or that adding two 100% systematics are correctly combined as non-correlated. Everything should now be correct, hopefully :pray: 

Some things are still missing, like ~~unit tests~~ and some error handling, but it's at least ready for review and comments.

### CODE REVIEW

**Comment by OlivierBondu** [comment]
At first glance it looks ok to me, the integration fails because of the plot comparison, as one would expect

the additional histograms would be created upstream with `histFactory` ? If so, I did not check but it would be great if the naming convention chosen here is the same as the one used for combine input shapes... to kill two birds with one stone, but I guess this was (one of) the idea behind this PR ?

**Comment by OlivierBondu** [comment]
actually another thing: there seems to be an additional continuous line joining the bins of the MC in http://i.imgur.com/VNnJj6Z.png, I cannot spot what could be at the origin of this...

**Comment by blinkseb** [comment]
The funny lines should be fixed, it was actually a memory corruption, so at least tests are usefully \o/ But I see it's still failing while it worked for me locally...

Concerning combine, there's no defined naming convention, as you have to declare yours at the beginning of the card (not sure if there's one by default), so we can always have something compatible, but it's easy to change it before merging (after too, but there's always a risk to break existing plots)

I don't have a clear idea on how we'll generate these plots :smiling: it'd be easier with `histFactory` to go with the second method (a file per type of plot) I guess... But first one should be doable with some tweaking!

Thanks for looking at it :)

**Comment by OlivierBondu** [comment]
well from what I [copied blindly](https://github.com/cp3-llbb/HHStatAnalysis/blob/f817e9f314f412d0c54d8f2c0877aa4436098e39/doDatacards.py#L193-L196) from `combineHarvester` package a few days ago the name of the histograms can indeed be customized... so since this PR is kind of upstream I don't mind much !

I guess having all histos in one file on the combine side would be easier to handle on the datacard-writing end...

as for how to generate the plots, I guess it is an open item as you say, since we would most very probably like to propagate any kind of systematic to the mva output which is run as a separate step at the moment

**Comment by blinkseb** [comment]
On my side, this is ready :)

**Comment by OlivierBondu** [comment]
oops sorry, I did not see the updated commits

merging now, thanks !

**Comment by blinkseb** [comment]
Don't worry I pushed them one hour ago ;)

**Pull request merged**
