### PR TITLE
Fix building of externals

### PR DESCRIPTION
**Pull request by swertz**
Fix script fetching yaml-cpp

### CODE REVIEW

**Comment by blinkseb** [comment]
What is the issue here? Old link seems to be working

**Comment by swertz** [comment]
Indeed, but that's not the issue... On ingrid, I first got:

```
curl -O -J -L https://github.com/jbeder/yaml-cpp/archive/release-0.5.3.tar.gz
curl: option -J: is unknown
curl: try 'curl --help' or 'curl --manual' for more information
```

Too old version I guess?
And then of course the `tar` command failed because the file name was not correct: `yaml-cpp-release-0.5.3.tar.gz` instead of `release-0.5.3.tar.gz`. 

Would you like me to revert the link back?

**Comment by blinkseb** [comment]
No it's fine :) I guess you're outside of a CMSSW env? `curl` version on ingrid must be older.

However, you now have unrelated changes in the PR. Can you revert?

**Comment by swertz** [comment]
Yes, that's it ;) Done!

**Pull request merged**
